name: Test

on:
  push:
    branches: master
  pull_request:

jobs:

  test:
    strategy:
      matrix:
        network: [standalone]
        dockerfile: [Dockerfile, Dockerfile.testing]
        options: ["", --enable-horizon-captive-core]
        exclude:
          - network: testnet
            options: --enable-horizon-captive-core
          - network: pubnet
            options: --enable-horizon-captive-core
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Stellar-Core Image
      if: ${{ matrix.dockerfile == 'Dockerfile.testing' }}
      run: docker build -t stellar/stellar-core:testing -f docker/Dockerfile.testing git://github.com/stellar/stellar-core-experimental-cap21and40#cap21and40 --build-arg CONFIGURE_FLAGS='--disable-tests'

    - name: Build Stellar-Horizon Image
      if: ${{ matrix.dockerfile == 'Dockerfile.testing' }}
      run: docker build -t stellar/stellar-horizon:dev -f services/horizon/docker/Dockerfile.dev git://github.com/stellar/go#cap21and40

    - name: Build Quickstart Image
      run: docker build -t stellar/quickstart -f ${{ matrix.dockerfile }} .

    - name: Run Quickstart Image
      run: docker run --rm -d -p "8000:8000" --name stellar stellar/quickstart --${{ matrix.network }} ${{ matrix.options }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1

    - name: Sleep until supervisor is up
      run: sleep 10

    - name: Run test
      run: |
        echo "supervisorctl tail -f stellar-core" | docker exec -i stellar sh &
        echo "supervisorctl tail -f horizon" | docker exec -i stellar sh &
        go run test.go
